language: python
python:
- 3.7-dev
install:
- pip install -r requirements.txt
script:
- pytest
before_install:
- mkdir secrets
- openssl aes-256-cbc -K $encrypted_2e2f0cb2fc6c_key -iv $encrypted_2e2f0cb2fc6c_iv
  -in creds.txt.enc -out secrets/creds.txt -d
