language: python
python:
- 3.7-dev
install:
- pip install -r requirements.txt
script:
- pytest
# env:
  # global:
    # secure: F8dIYvBUkftlxlReHEQRYQtLr+zFV642N6bp57APs9s7WWpAjfkn+Mi1M8z7ZBcgpHyBaVm1aD0CYvPyYiixPixZu3tsPHCoB7NeVwtmtaEa7eTsj0n7D7/o2bD6hrKekse0NUQOAkRRXxV0JtODoYO7RI4zD16SlOarhuJpIsPZ6MghXDgZXiGWPDEvI6YuMQIARtOqsyiFIlizysUCWo/SYb3u+D5GdzwMtrkH/GzQwe/ZyfZaXheb1ElqQk61AInCIXdeXUR8KrXUWAyxSa6KSUnKGpj06s9e96CRmiWmJnaaR3IYc2+NsHFwZ8ip7U03Mho8REWQ+ikxWSLI+29NFjTrcVq1dwIGapCrJHlP3aUfB67+Z8P3DuzNmUi0gBk0aAW+1G48OSGGc5lq3rwpwJ0CKRz2CL7tW7YyDQlm7FxGlLjr2YR2hlslc1cxni413JrwrinLcg+Omcggw0iEp3nTanwofrIsSUtn9xZtHM9556y9Mz1jAgpAONZVatWDpD6eGLMxhauIP8hHEuTuojOPE/ApMULY2pZM78NWH3Kbo6dmeE15t9IBYnsB6QPM5MZ7N2x6LXVDYXx93/+xBSqrr8IRbuF3s2Cc9xSjRbrdIBEBRrSK7Dpt5AKrC3frY0sfCFVXGzaKXfhMaw3AzDsPSPqNyBU07ESREkM=
before_install:
- openssl aes-256-cbc -K $encrypted_2e2f0cb2fc6c_key -iv $encrypted_2e2f0cb2fc6c_iv
  -in creds.txt.enc -out secrets/creds.txt -d
- mkdir secrets
- mv creds.txt secrets/creds.txt
